#!/usr/bin/env node
// Applies brand.config.json across the extension. Idempotent: running it twice
// with the same config produces byte-identical output. Pure Node built-ins, no
// dependencies.
//
//   node scripts/rebrand.mjs
//
// What it writes, all derived from brand.config.json:
//   - src/manifest.json                  name, description, icons, narrowed
//                                         host_permissions / content_scripts
//   - src/config/brand.generated.ts      the BRAND object imported across src/
//   - src/entries/Popup/theme.generated.css   CSS color tokens
//   - popup.html <title>
//   - src/assets/img + src/assets/dev    icons copied from iconDir
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const log = (msg) => console.log(`  ${msg}`);
const fail = (msg) => {
  console.error(`rebrand: ${msg}`);
  process.exit(1);
};

// ---------------------------------------------------------------- load + validate
const configPath = path.join(root, 'brand.config.json');
if (!existsSync(configPath)) fail('brand.config.json not found.');

let config;
try {
  config = JSON.parse(readFileSync(configPath, 'utf-8'));
} catch (error) {
  fail(`brand.config.json is not valid JSON: ${error.message}`);
}

const REQUIRED = [
  'name',
  'shortName',
  'description',
  'vendorId',
  'theme',
  'iconDir',
  'hostDomains',
  'appOrigins',
  'attestationServiceUrl',
  'apiBaseUrl',
];
for (const key of REQUIRED) {
  if (config[key] === undefined || config[key] === null) fail(`brand.config.json is missing "${key}".`);
}
if (!Array.isArray(config.hostDomains) || config.hostDomains.length === 0) {
  fail('hostDomains must be a non-empty array of match patterns.');
}
if (!Array.isArray(config.appOrigins) || config.appOrigins.length === 0) {
  fail('appOrigins must be a non-empty array of match patterns.');
}
if (!/^[a-z0-9][a-z0-9-]*$/.test(config.vendorId)) {
  fail('vendorId must be a lowercase slug (a-z, 0-9, hyphens), e.g. "acme-verify".');
}

const THEME_KEYS = ['brand', 'brandContrast', 'accent', 'background', 'surface', 'text', 'muted'];
for (const key of THEME_KEYS) {
  if (typeof config.theme[key] !== 'string') fail(`theme.${key} must be a color string.`);
}

console.log(`\nRebranding to "${config.name}" (vendor: ${config.vendorId})\n`);

// ---------------------------------------------------------------- derivations
const originWithGlob = (url) => `${new URL(url).origin}/*`;
const apiBaseUrl = config.apiBaseUrl.replace(/\/+$/, '');
const attestationServiceUrl = config.attestationServiceUrl.replace(/\/+$/, '');
const providerTemplateApiRoot = `${apiBaseUrl}/providers/`;

const stripGlob = (pattern) => pattern.replace(/\/\*?$/, '');
const webUrl = stripGlob(
  config.appOrigins.find((p) => !p.includes('localhost') && !p.includes('*.')) ??
    config.appOrigins[0],
);

// ---------------------------------------------------------------- manifest.json
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf-8'));
const ICONS = ['16', '32', '48', '128'];

const manifest = {
  manifest_version: 3,
  name: config.name,
  version: pkg.version,
  description: config.description,
  icons: Object.fromEntries(ICONS.map((s) => [s, `icon-${s}.png`])),
  action: {
    default_icon: 'icon-48.png',
    default_title: config.name,
    default_popup: 'popup.html',
  },
  background: { service_worker: 'background.bundle.js', type: 'module' },
  content_security_policy: {
    extension_pages: "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'; frame-ancestors 'none';",
  },
  content_scripts: [
    { matches: config.hostDomains, all_frames: false, js: ['txClickGuideLoader.bundle.js'] },
    { matches: config.appOrigins, all_frames: false, js: ['contentScriptLoader.bundle.js'] },
  ],
  web_accessible_resources: [
    {
      resources: [
        'contentScript.bundle.js',
        'txClickGuide.bundle.js',
        '*.chunk*.js',
        ...ICONS.map((s) => `icon-${s}.png`),
        'injectScript.bundle.js',
      ],
      matches: [...config.hostDomains, ...config.appOrigins],
    },
  ],
  host_permissions: [
    ...config.hostDomains,
    ...config.appOrigins,
    originWithGlob(apiBaseUrl),
    originWithGlob(attestationServiceUrl),
  ],
  permissions: ['offscreen', 'webRequest', 'tabs', 'scripting'],
};

writeFileSync(path.join(root, 'src/manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
log('wrote src/manifest.json');

// ---------------------------------------------------------------- brand.generated.ts
const j = (value) => JSON.stringify(value);
const brandTs = `// AUTO-GENERATED by scripts/rebrand.mjs from brand.config.json.
// Do not edit by hand. Your changes will be overwritten on the next rebrand.
// Edit brand.config.json and run \`npm run rebrand\` instead.

export interface BrandTheme {
  /** Primary brand color (buttons, accents, spinner). */
  brand: string;
  /** Readable text/icon color when placed on top of \`brand\`. */
  brandContrast: string;
  /** Secondary accent used in gradients and highlights. */
  accent: string;
  /** Popup canvas background. */
  background: string;
  /** Popup card / elevated surface. */
  surface: string;
  /** Primary text color in the popup. */
  text: string;
  /** Secondary text color in the popup. */
  muted: string;
}

export interface Brand {
  /** Full product name (manifest name, popup title). */
  name: string;
  /** Compact name for tight UI. */
  shortName: string;
  /** Store / manifest description. */
  description: string;
  /** Value written to \`data-peer-vendor\` so host apps can identify the extension. */
  vendorId: string;
  /** Base URL of the Peer API (provider templates live under /providers/). */
  apiBaseUrl: string;
  /** Base URL of the attestation service that verifies encrypted captures. */
  attestationServiceUrl: string;
  /** Derived: \`\${apiBaseUrl}/providers/\`. */
  providerTemplateApiRoot: string;
  /** The host app's primary web URL, opened when the toolbar icon is clicked. */
  webUrl: string;
  /** Match patterns for payment-platform hosts that may receive the click-guide. */
  hostDomains: string[];
  /** Match patterns for host app origins that may use window.peer. */
  appOrigins: string[];
  /** Brand color tokens. */
  theme: BrandTheme;
}

export const BRAND: Brand = {
  name: ${j(config.name)},
  shortName: ${j(config.shortName)},
  description:
    ${j(config.description)},
  vendorId: ${j(config.vendorId)},
  apiBaseUrl: ${j(apiBaseUrl)},
  attestationServiceUrl: ${j(attestationServiceUrl)},
  providerTemplateApiRoot: ${j(providerTemplateApiRoot)},
  webUrl: ${j(webUrl)},
  hostDomains: ${j(config.hostDomains)},
  appOrigins: ${j(config.appOrigins)},
  theme: {
    brand: ${j(config.theme.brand)},
    brandContrast: ${j(config.theme.brandContrast)},
    accent: ${j(config.theme.accent)},
    background: ${j(config.theme.background)},
    surface: ${j(config.theme.surface)},
    text: ${j(config.theme.text)},
    muted: ${j(config.theme.muted)},
  },
};
`;
writeFileSync(path.join(root, 'src/config/brand.generated.ts'), brandTs);
log('wrote src/config/brand.generated.ts');

// ---------------------------------------------------------------- theme.generated.css
const themeCss = `/* AUTO-GENERATED by scripts/rebrand.mjs from brand.config.json.
 * Do not edit by hand. Edit brand.config.json and run \`npm run rebrand\`. */
:root {
  --brand: ${config.theme.brand};
  --brand-contrast: ${config.theme.brandContrast};
  --accent: ${config.theme.accent};
  --background: ${config.theme.background};
  --surface: ${config.theme.surface};
  --text: ${config.theme.text};
  --muted: ${config.theme.muted};
}
`;
writeFileSync(path.join(root, 'src/entries/Popup/theme.generated.css'), themeCss);
log('wrote src/entries/Popup/theme.generated.css');

// ---------------------------------------------------------------- popup.html <title>
const popupHtmlPath = path.join(root, 'popup.html');
const popupHtml = readFileSync(popupHtmlPath, 'utf-8').replace(
  /<title>[^<]*<\/title>/,
  `<title>${config.name}</title>`,
);
writeFileSync(popupHtmlPath, popupHtml);
log('updated popup.html title');

// ---------------------------------------------------------------- icons
const iconSrcDir = path.resolve(root, config.iconDir);
let copied = 0;
let missing = 0;
for (const dest of ['src/assets/img', 'src/assets/dev']) {
  const destDir = path.join(root, dest);
  mkdirSync(destDir, { recursive: true });
  for (const size of ICONS) {
    const file = `icon-${size}.png`;
    const from = path.join(iconSrcDir, file);
    if (existsSync(from)) {
      copyFileSync(from, path.join(destDir, file));
      copied += 1;
    } else {
      missing += 1;
    }
  }
}
if (missing > 0) {
  log(`icons: copied ${copied}, ${missing} missing from ${config.iconDir}/ (add icon-16/32/48/128.png)`);
} else {
  log(`icons: copied ${copied} into src/assets/img and src/assets/dev`);
}

console.log(`\nDone. Review the diff, then run: npm run build\n`);
