// AUTO-GENERATED by scripts/rebrand.mjs from brand.config.json.
// Do not edit by hand — your changes will be overwritten on the next rebrand.
// Edit brand.config.json and run `npm run rebrand` instead.

export interface BrandTheme {
  /** Primary brand color (buttons, accents, spinner). */
  brand: string;
  /** Readable text/icon color when placed on top of `brand`. */
  brandContrast: string;
  /** Secondary accent used in gradients and highlights. */
  accent: string;
  /** Popup canvas background. */
  background: string;
  /** Popup card / elevated surface. */
  surface: string;
  /** Primary text color in the popup. */
  text: string;
  /** Secondary / muted text color in the popup. */
  muted: string;
}

export interface Brand {
  /** Full product name (manifest name, popup title). */
  name: string;
  /** Compact name for tight UI ("Secured by …", chips). */
  shortName: string;
  /** Store / manifest description. */
  description: string;
  /** Value written to the `data-peer-vendor` page attribute so host apps can
   *  attribute which window.peer implementation served a session. */
  vendorId: string;
  /** Base URL of the Peer API (provider templates live under /providers/). */
  apiBaseUrl: string;
  /** Base URL of the attestation service that issues proofs. */
  attestationServiceUrl: string;
  /** Derived: `${apiBaseUrl}/providers/`. */
  providerTemplateApiRoot: string;
  /** The host app's primary web URL, opened when the toolbar icon is clicked. */
  webUrl: string;
  /** Match patterns for the host app origins that may use window.peer. */
  appOrigins: string[];
  /** Brand color tokens. */
  theme: BrandTheme;
}

export const BRAND: Brand = {
  name: "Acme Verify",
  shortName: "Acme Verify",
  description:
    "Securely verify your payments with privacy-preserving proofs — no passwords or screenshots leave your device.",
  vendorId: "acme-verify",
  apiBaseUrl: "https://api.zkp2p.xyz",
  attestationServiceUrl: "https://attestation-service.zkp2p.xyz",
  providerTemplateApiRoot: "https://api.zkp2p.xyz/providers/",
  webUrl: "https://app.acme-verify.example",
  appOrigins: ["https://app.acme-verify.example/*","http://localhost/*"],
  theme: {
    brand: "#4f46e5",
    brandContrast: "#ffffff",
    accent: "#06b6d4",
    background: "#0b0b12",
    surface: "#15151f",
    text: "#f5f5fa",
    muted: "#a1a1b5",
  },
};
