// AUTO-GENERATED by scripts/rebrand.mjs from brand.config.json.
// Do not edit by hand. Your changes will be overwritten on the next rebrand.
// Edit brand.config.json and run `npm run rebrand` instead.

export interface BrandTheme {
  /** Primary brand color (buttons, accents, spinner). */
  brand: string;
  /** Readable text/icon color when placed on top of `brand`. */
  brandContrast: string;
  /** Secondary accent used in gradients and highlights. */
  accent: string;
  /** Popup canvas background. */
  background: string;
  /** Popup card / elevated surface. */
  surface: string;
  /** Primary text color in the popup. */
  text: string;
  /** Secondary text color in the popup. */
  muted: string;
}

export interface Brand {
  /** Full product name (manifest name, popup title). */
  name: string;
  /** Compact name for tight UI. */
  shortName: string;
  /** Store / manifest description. */
  description: string;
  /** Value written to `data-peer-vendor` so host apps can identify the extension. */
  vendorId: string;
  /** Base URL of the Peer API (provider templates live under /providers/). */
  apiBaseUrl: string;
  /** Base URL of the attestation service that verifies encrypted captures. */
  attestationServiceUrl: string;
  /** Derived: `${apiBaseUrl}/providers/`. */
  providerTemplateApiRoot: string;
  /** The host app's primary web URL, opened when the toolbar icon is clicked. */
  webUrl: string;
  /** Match patterns for payment-platform hosts that may receive the click-guide. */
  hostDomains: string[];
  /** Match patterns for host app origins that may use window.peer. */
  appOrigins: string[];
  /** Brand color tokens. */
  theme: BrandTheme;
}

export const BRAND: Brand = {
  name: "Acme Verify",
  shortName: "Acme Verify",
  description:
    "Verify payments without sharing passwords or screenshots.",
  vendorId: "acme-verify",
  apiBaseUrl: "https://api.zkp2p.xyz",
  attestationServiceUrl: "https://attestation-service.zkp2p.xyz",
  providerTemplateApiRoot: "https://api.zkp2p.xyz/providers/",
  webUrl: "https://app.acme-verify.example",
  hostDomains: ["https://*.example-bank.com/*","https://*.example-payments.com/*","https://*.example-pay.com/*"],
  appOrigins: ["https://app.acme-verify.example/*","http://localhost/*"],
  theme: {
    brand: "#4f46e5",
    brandContrast: "#ffffff",
    accent: "#06b6d4",
    background: "#0b0b12",
    surface: "#15151f",
    text: "#f5f5fa",
    muted: "#a1a1b5",
  },
};
